### ISSUE TITLE
As a Person, I want to reset my password so that I can login

### ISSUE THREAD

**Issue by maheshkhanwalkar** [maheshkhanwalkar/BuzzShelter#20]

**Comment by ykding** [comment]
Tasks:
•	Add “Forget password” button to request password reset at login page.
•	Add views for “forget password” page
•	Create a ForgetPasswordActivity and associated controller
•	Hook with email service
•	Add views for resetting password for logged in user.
•	Create a ResetPasswordActivity and associated controller

Acceptance Scenarios
Scenario 1: A user forgets his(her) password and can’t login.
•	GIVEN: The user is at login page and clicks “forget password” button. WHEN: The user inputs valid email address of one of the user in database at the “forget password” page. THEN: 	The server generates a secure link to reset password of this user with a certain time to live. The server sends an email with this link to the email address. The app shows message of successfully sending email.

•	GIVEN: 	The user is at login page and clicks “forget password” button. WHEN: The user inputs invalid email address (incorrect format or this email address is not associated with user in database) at the “forget password” page. THEN: The app shows error message and asks user to try again.

Scenario 2: A user click the link from Scenario 1 to reset password 
•	GIVEN: The user is at reset password page. And there are two input fields with “new password” and “retype the password” tag. WHEN: The user inputs new password in valid format and retype it correctly. THEN: The app shows success message. The database updates the password of corresponding user. The app then redirects to the login page.

•	GIVEN: The user is at reset password page. And there are two input fields with “new password” and “retype the password” tag. WHEN: 	The user inputs new password in invalid format or retype the password incorrectly. THEN: The app shows error message, clears the input field and ask the user to retry. 

Scenario 3: A logged in user want to reset his(her) password.
•	GIVEN: The user is at reset password page. And there are three input fields with ”current password”, “new password” and “retype the password” tag. WHEN: The user inputs correct current password, new password in valid format and retype it correctly. THEN: The app shows success message. The database updates the password of corresponding user.

•	GIVEN: 	The user is at reset password page. And there is to input field with “new password” and “retype the password” tag. WHEN: The user inputs incorrect current password, new password in invalid format or retype the password incorrectly. THEN: The app shows error message, clears the input field and ask the user to retry. 

Done Done Criteria:
•	All Acceptance scenarios are met
•	The changes have been merged into ‘staging’ branch
•	Re-run tests to make sure the merged changes in ‘staging’ are still functional when included with the other pieces of the codebase
•	staging, along with other features, must be merged into master
