### ISSUE TITLE
As a User, I want to check into a shelter so that I can reserve a spot

### ISSUE THREAD

**Issue by maheshkhanwalkar** [maheshkhanwalkar/BuzzShelter#22]

**Comment by ekumala1** [comment]
**Tasks:**
Create a ShelterListActivity and associated controller
Add buttons for selecting specific shelters on User's side
Create ShelterDetailsActivity to contain more details about Shelter and associated controller
Add button for checking into shelter
Add views for displaying address, description, and eligibility requirements
If user is already checked in, display address details and other specific information. 

**Acceptance Scenarios:**
GIVEN a user is viewing the Shelter list page, WHEN the user selects a shelter on list, THEN the app will show details about the selected shelter.
GIVEN a user is viewing the Shelter list page, WHEN the user selects a shelter that is further than a mile, THEN the app will display a message stating that the shelter is further than a mile away, with buttons for "Continue" and "Cancel".
GIVEN a user is viewing the Shelter list page, WHEN the user selects a shelter that the user is ineligible for, THEN the app will display a message stating that the user is ineligible, with buttons for "Continue" and "Cancel".
GIVEN a user is viewing the Shelter details page and the user is eligible for the current shelter, WHEN the user chooses to check in to the shelter, a message will appear stating that they have successfully checked in.
GIVEN a user is viewing the Shelter details page and the user is ineligible for the current shelter, WHEN the user chooses to check in to the shelter, a message will appear stating that they have not met the necessary requirements.

**Done Done Criteria:**
All the acceptance scenarios have been met
The changes have been merged into ‘staging’ branch
Re-run tests to make sure the merged changes in ‘staging’ are still functional when included with the other pieces of the codebase
staging, along with other features, must be merged into master for M6
master has been tagged m6-demo to indicate the current spot is ready to be demoed for M6 (stable and working)
