### ISSUE TITLE
As an Admin, I want to be able to remove users so that I can stop account abuse and reduce spam to make the system more reliable

### ISSUE THREAD

**Issue by maheshkhanwalkar** [maheshkhanwalkar/BuzzShelter#25]

**Comment by kwang188** [comment]
Tasks:
•   Add “Remove User” button to the home page of an admin account
•   Add views for “Remove User” page
•   Create a Remove User Activity and associated controller

Acceptance Scenarios
•   GIVEN an Admin User is viewing the Admin Home page, WHEN the user clicks on the Remove User button, THEN the app will go to the Remove User Page which shows all the users except this admin user itself.
•   GIVEN a Admin User is viewing the Remove page, WHEN the user click on the Home button, THEN the app goes back to the Admin Home page.
•   GIVEN a Admin User is viewing the Remove page, WHEN the user click on an unselected/selected a user record, THEN the app will select/unselect the user and a Tick will appear/disappear beside that user record.
•   GIVEN a Admin User is viewing the Remove page, WHEN the user click on the Remove button, THEN all the selected user record will be removed and the Remove User Page will refresh.

Done Done Criteria:
•   All acceptance scenarios can be achieved
•   The changes have been merged into ‘staging’ branch
•   Re-run tests over code in ‘staging’ branch to make sure this feature works well with other features 
•   Staging branch is merged into master
